// Package secrets writes per-project DATABASE_URL env files atomically. It
// is the single place where MySQL user passwords appear in plaintext on
// disk, and it does so only on the server with restrictive permissions.
package secrets

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// Writer writes secrets to dir with the file-mode 0600. dir MUST already
// exist with root-only access; the Writer enforces per-file permissions.
type Writer struct {
	Dir string
}

// New returns a Writer rooted at dir. The directory is created with mode
// 0700 if it does not exist (best-effort — system administrators are
// expected to harden the path).
func New(dir string) (*Writer, error) {
	if dir == "" {
		return nil, errors.New("secrets dir is required")
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, fmt.Errorf("mkdir %q: %w", dir, err)
	}
	return &Writer{Dir: dir}, nil
}

// Path returns the canonical on-disk path for a project.
func (w *Writer) Path(name string) string {
	return filepath.Join(w.Dir, name+".env")
}

// Secret holds the values written into a project env file.
type Secret struct {
	Name     string
	Database string
	User     string
	Password string
}

// Write atomically writes the env file for the given project. The result is
// fsync'd then renamed into place so an interrupted write cannot leave a
// half-written file behind.
func (w *Writer) Write(s Secret) (string, error) {
	if s.Name == "" || s.Database == "" || s.User == "" || s.Password == "" {
		return "", errors.New("secret fields must all be set")
	}
	if err := validateIdentifier(s.Name); err != nil {
		return "", err
	}
	if err := validateIdentifier(s.Database); err != nil {
		return "", err
	}
	if err := validateIdentifier(s.User); err != nil {
		return "", err
	}
	final := w.Path(s.Name)
	tmp, err := os.CreateTemp(w.Dir, "."+s.Name+".*.tmp")
	if err != nil {
		return "", fmt.Errorf("create temp: %w", err)
	}
	tmpName := tmp.Name()
	defer func() {
		_ = os.Remove(tmpName) // no-op if rename succeeded
	}()

	body := renderEnv(s)
	if _, err := tmp.Write([]byte(body)); err != nil {
		tmp.Close()
		return "", fmt.Errorf("write temp: %w", err)
	}
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return "", fmt.Errorf("chmod temp: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return "", fmt.Errorf("fsync temp: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return "", fmt.Errorf("close temp: %w", err)
	}
	if err := os.Rename(tmpName, final); err != nil {
		return "", fmt.Errorf("rename: %w", err)
	}
	// Best-effort fsync of the directory so the rename is durable on most
	// filesystems.
	if d, err := os.Open(w.Dir); err == nil {
		_ = d.Sync()
		_ = d.Close()
	}
	return final, nil
}

// Delete removes the env file for the given project. Missing files are not
// an error so callers can use this idempotently.
func (w *Writer) Delete(name string) error {
	if err := validateIdentifier(name); err != nil {
		return err
	}
	err := os.Remove(w.Path(name))
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return nil
}

func renderEnv(s Secret) string {
	// Note: the connection string uses 127.0.0.1 explicitly — MySQL treats
	// 127.0.0.1 and localhost differently for the purposes of user-host
	// matching, and we provision users on both hosts.
	dsn := "mysql://" + s.User + ":" + s.Password + "@127.0.0.1:3306/" + s.Database
	var b strings.Builder
	b.WriteString("# Auto-generated by db-isolation. Do not edit by hand.\n")
	b.WriteString("# Permissions: 0600. Mode of access: server-local only.\n")
	b.WriteString("DATABASE_URL=")
	b.WriteString(dsn)
	b.WriteString("\n")
	b.WriteString("DB_HOST=127.0.0.1\n")
	b.WriteString("DB_PORT=")
	b.WriteString(strconv.Itoa(3306))
	b.WriteString("\n")
	b.WriteString("DB_NAME=")
	b.WriteString(s.Database)
	b.WriteString("\n")
	b.WriteString("DB_USER=")
	b.WriteString(s.User)
	b.WriteString("\n")
	b.WriteString("DB_PASSWORD=")
	b.WriteString(s.Password)
	b.WriteString("\n")
	return b.String()
}

// validateIdentifier accepts the characters we use for on-disk filenames
// (project names like "iximei-kf"). This is intentionally broader than
// what MySQL identifiers allow — secret files live on the Linux FS, not
// in MySQL. The MySQL identifier check is enforced separately by
// mysqlx.assertIdentifier.
//
// Allowed: ASCII letters, digits, hyphen, underscore, period.
func validateIdentifier(s string) error {
	if s == "" {
		return errors.New("identifier is required")
	}
	if len(s) > 64 {
		return errors.New("identifier too long")
	}
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z':
		case r >= 'A' && r <= 'Z':
		case r >= '0' && r <= '9':
		case r == '-' || r == '_' || r == '.':
		default:
			return fmt.Errorf("invalid identifier %q", s)
		}
	}
	return nil
}